language: cpp

notifications:
  email: false
  
sudo: required
dist: trusty

os:
  - linux
  - osx

branches:
  only:
    - master
    
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-5
    - g++-5
    - flex
    - bison
    
before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi
  
  - if [[ $OSX ]]; then brew update; fi

install:
  - wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
  - sudo sh cmake-3.3.1-Linux-x86_64.sh --skip-license --prefix=/usr
  #- if [[ $LINUX ]]; then sudo apt-get update; fi
  #- if [[ $LINUX ]]; then sudo apt-get install -y bison flex; fi
  - if [[ $LINUX && "$CXX" = "g++"     ]]; then export CXX="g++-5"       CC="gcc-5";     fi
  #- if [[ $OSX   && "$CXX" = "clang++" ]]; then export CXX="clang++-3.7" CC="clang-3.7"; fibefore_install:
  
  - if [[ $OSX ]]; then brew install llvm --with-clang; fi
  - if [[ $OSX ]]; then clang --version; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ctest -j2
