language: cpp

notifications:
  email: false
  
#sudo: required
#dist: trusty

#sudo: false

os:
  - linux
  #- osx

branches:
  only:
    - master
    
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    #- llvm-toolchain-precise
    packages:
    - gcc-5
    - g++-5
    - cmake
    - flex
    - bison
    
before_install:
  - if [[ $TRAVIS_OS_NAME == linux   ]]; then LINUX=true; fi
  - if [[ $TRAVIS_OS_NAME == osx     ]]; then OSX=true; fi

install:
  #- if [[ $OSX  ]]; then wget --no-check-certificate http://www.cmake.org/files/v3.3/cmake-3.3.1-Linux-x86_64.sh
  #- if [[ $OSX  ]]; then sudo sh cmake-3.3.1-Linux-x86_64.sh --skip-license --prefix=/usr
  #- if [[ $LINUX ]]; then sudo apt-get update; fi
  #- if [[ $LINUX ]]; then sudo apt-get install -y bison flex; fi
  #- if [[ $LINUX && "$CXX" = "g++"     ]]; then export CXX="g++-5"       CC="gcc-5";     fi
  #- if [[ $OSX   && "$CXX" = "clang++" ]]; then export CXX="clang++-3.7" CC="clang-3.7"; fi

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ctest -j2
