os: Visual Studio 2015

platform:
  - x86
  - x64

configuration:
  - Release

before_build:
  - if %platform%==x86 set generator=Visual Studio 14 2015
  - if %platform%==x64 set generator=Visual Studio 14 2015 Win64
  - if %platform%==x86 set vcplatform=Win32
  - if %platform%==x64 set vcplatform=x64
  - echo %platform%
  - echo %vcplatform%
  - echo %configuration%
  - echo %PLATFORM%
  - echo %CONFIGURATION%

build_script:
  - mkdir build
  - cd build
  - cmake .. -G "%generator%"
  - msbuild flex.sln /p:Platform=%vcplatform% /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - ctest
